version: '3.8'

services:
  web:
    build: ./docker
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/html
      - ./src:/var/www/api
      - ./data:/var/www/data
    restart: unless-stopped
